# Generated by Django 5.2.4 on 2025-07-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('treadDiameterNew', models.CharField(max_length=100)),
                ('lastShopIssueSize', models.CharField(max_length=100)),
                ('condemningDia', models.CharField(max_length=100)),
                ('wheelGauge', models.CharField(max_length=100)),
                ('variationSameAxle', models.CharField(max_length=100)),
                ('variationSameBogie', models.CharField(max_length=100)),
                ('variationSameCoach', models.CharField(max_length=100)),
                ('wheelProfile', models.CharField(max_length=100)),
                ('intermediateWWP', models.CharField(max_length=100)),
                ('bearingSeatDiameter', models.CharField(max_length=100)),
                ('rollerBearingOuterDia', models.CharField(max_length=100)),
                ('rollerBearingBoreDia', models.CharField(max_length=100)),
                ('rollerBearingWidth', models.CharField(max_length=100)),
                ('axleBoxHousingBoreDia', models.CharField(max_length=100)),
                ('wheelDiscWidth', models.CharField(max_length=100)),
                ('status', models.CharField(default='Saved', max_length=20)),
            ],
        ),
    ]
